version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node 20..."
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs

      # 🔥 VERY IMPORTANT FIX
      - export PATH=/usr/bin:$PATH
      - hash -r

      - node -v   # should show v20+

  build:
    commands:
      - echo "Building backend..."
      - cd backend
      - mvn clean package -DskipTests
      - cd ..

      - echo "Building frontend..."
      - cd frontend
      - npm install
      - npm run build
      - cd ..

artifacts:
  files:
    - backend/target/*.jar
    - frontend/build/**/*
    - appspec.yml
    - scripts/**/*