version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Building backend..."
      - cd backend
      - mvn clean package
      - cd ..

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - backend/target/*.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: yes